" _          _
"| |__   ___| |_ ___
"| '_ \ / _ \ __/ _ \
"| |_) |  __/ || (_) |
"|_.__/ \___|\__\___/
"

".vimrc

" init plugin
call plug#begin('~/.vim/plugged')

" nord theme
Plug 'arcticicestudio/nord-vim'

" button toolbar
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" git manager
Plug 'tpope/vim-fugitive'

" git diff in the sign column
Plug 'airblade/vim-gitgutter'

" file explorer
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'

" autocompletion
Plug 'neoclide/coc.nvim', { 'branch': 'release' }

" golang support
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

call plug#end()

syntax on

colorscheme nord

set background=dark
set encoding=utf-8
set autowrite
"set list!
"set listchars=tab:>-,trail:·
set backspace=indent,eol,start
set t_Co=256
set number
set relativenumber
set colorcolumn=80
set cursorline
set spell spelllang=en
set spellfile=~/.vim/spell/en.utf-8.add
set foldmethod=indent
set foldlevel=99

" config toolbar
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#formatter = 'unique_tail'

" config vim-go
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_build_constraints = 1

" block arrow keys
map <Left> <Nop>
map <Up> <Nop>
map <Right> <Nop>
map <Down> <Nop>

" autocomplete surronders
ino " ""<left>
ino ' ''<left>
ino ( ()<left>
ino [ []<left>
ino { {}<left>

" toggle nerdTree
map <F8> :NERDTreeToggle<CR>
